### ISSUE TITLE
[Feature request] A prop to change the value of `useNativeDriver`

### ISSUE THREAD

**Issue by SimpleCreations** [mmazzarolo/react-native-dialog#119]
I have a scenario where a lot of work is performed while the dialog has its closing animation, and on older iOS devices this results in the animation visibly lagging, because `useNativeDriver` is set to `false` and the animation runs on the UI thread. Patching the source and setting the value to `true` makes the animation smooth.

[This line](https://github.com/mmazzarolo/react-native-dialog/blob/master/src/Modal.tsx#L131) reports a problem with this option, however I haven't noticed any flashes at all (tested on iOS 12 and iOS 14). I suggest making `useNativeDriver` available as a `Dialog.Container` prop and set it to `false` by default, this way if someone doesn't experience the flashes and wants smoother animations, they can opt-in.

**Comment by mmazzarolo** [comment]
I'm ok with that, if you're ok with creating a PR for it 👍 
I'm not even 100% sure we should still default it to `false` since IIRC the RN team recently made some changes to the Modal.  
FYI the issue was mostly on the Android side (on iOS, using a Modal without any `animationType` was enough to fix it). 

More info here:
- https://github.com/react-native-modal/react-native-modal/issues/92
- https://github.com/facebook/react-native/issues/21552
