### ISSUE TITLE
Is separator border removable?

### ISSUE THREAD

**Issue by domoretrix** [mmazzarolo/react-native-dialog#135]
## Is there a way to remove the horizontal hairline width separator border?
<img width="207" alt="Screen Shot 2022-03-31 at 12 11 24 AM" src="https://user-images.githubusercontent.com/34522983/160932283-7a464461-bbbc-4f15-9e8f-2a3932992afd.png">

**Comment by mmazzarolo** [comment]
If I may ask: why? Doesn't the native iOS dialog show it? 🤔

**Comment by domoretrix** [comment]
It does show it, that’s the problem, I want it off. I have to make the alert view look as one whole unseparated view. I’ve tried playing with borderTopWidth and borderBottomWidth in headerStyle and footerStyle, but no luck. I haven’t looked through your code but as far it seems like it’s part of a different component that I have no access to its style. That’s why I’m asking.

**Comment by mmazzarolo** [comment]
What I'm saying is: does the native iOS dialog (not the one from `react-native-dialog`) show it?  
I'm asking this because the goal of this component is to mimic the native dialog, allowing only the minimum surface area for customization. At the moment, I don't think there's an easy way to customize the border, but if the native iOS dialog does not show it, we can update `react-native-dialog` to do the same.

**Comment by domoretrix** [comment]
Yes, the native iOS does show the horizontal border. Ya, I mean it would be nice if it could be customized in this sense. At least in my case ...

**Comment by mmazzarolo** [comment]
Gotcha. Sorry, but for the time being I prefer to not expand the API.
